export const steels = [
  {
    name: "A36",
    img: "../../../assets/Images/steels/steel1.jpg",
    yield: 250,
    ultimate: 400,
    elongation: 18,
    price: 150,
  },
  {
    name: "A572",
    img: "../../../assets/Images/steels/steel2.jpg",
    yield: 300,
    ultimate: 500,
    elongation: 20,
    price: 160,
  },
  {
    name: "A992",
    img: "../../../assets/Images/steels/steel3.jpg",
    yield: 350,
    ultimate: 550,
    elongation: 22,
    price: 170,
  },
  {
    name: "A500",
    img: "../../../assets/Images/steels/steel4.jpg",
    yield: 320,
    ultimate: 480,
    elongation: 19,
    price: 155,
  },
  {
    name: "A1065",
    img: "../../../assets/Images/steels/steel5.jpg",
    yield: 400,
    ultimate: 600,
    elongation: 25,
    price: 180,
  },
  {
    name: "A1085",
    img: "../../../assets/Images/steels/steel3.jpg",
    yield: 420,
    ultimate: 620,
    elongation: 27,
    price: 190,
  },
  {
    name: "A1090",
    img: "../../../assets/Images/steels/steel1.jpg",
    yield: 450,
    ultimate: 650,
    elongation: 30,
    price: 200,
  },
];
